# Install clojure
# ARG INSTALL_CLOJURE="true"
COPY custom-scripts/clojure/* /tmp/library-scripts/
RUN bash /tmp/library-scripts/install-clojure.sh "${USERNAME}" \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/