(module 
    (memory $mem 1)
  (global $CROWN i32 (i32.const 4))
  (global $WHITE i32 (i32.const 1))
  (global $BLACK i32 (i32.const 2))
    (func $indexForPosition (param $x i32) (param $y i32) (result i32)
        (i32.add 
            (i32.mul
                (i32.const 8)
                (get_local $y)
            )
            (get_local $x)
        )
    )
    (func $offsetForPosition (param $x i32) (param $y i32) (result i32)
        (i32.mul 
            (call $indexForPosition (get_local $x) (get_local $y))
            (i32.const 4)
        )
    )
    (func $isWhite (param $piece i32) (result i32)
          (i32.eq 
            (i32.and (get_local $piece) (get_global $WHITE))
            (get_global $WHITE)
          )
          )
    (func $isBlack (param $piece i32) (result i32)
          (i32.eq 
            (i32.and (get_local $piece) (get_global $BLACK))
            (get_global $BLACK)
          )
          )
    (func $isCrowned (param $piece i32) (result i32)
          (i32.eq 
            (i32.and (get_local $piece) (get_global $CROWN))
            (get_global $CROWN)
          )
          )
         
   (func $addCrown (param $piece i32) (result i32)
         (i32.or (get_local $piece) (get_global $CROWN))
         ) 
   (func $removeCrown (param $piece i32) (result i32)
         (i32.and (get_local $piece) (i32.const 3))
         ) 
   
   (export "offsetForPosition" (func $offsetForPosition))
   (export "isWhite" (func $isWhite))
   (export "isBlack" (func $isBlack))
   (export "isCrowned" (func $isCrowned))
   (export "addCrown" (func $addCrown))
   (export "removeCrown" (func $removeCrown))
)